### ISSUE TITLE
URL of homepage of Toda Laboratory is too old

### ISSUE THREAD

**Issue by tats-u** [JeremyCCHsu/JeremyCCHsu.github.io#1]
https://github.com/JeremyCCHsu/JeremyCCHsu.github.io/blob/393f5f213cad5b8e9ea1a2d755fe581a4355e72e/index.html#L71

This URL is too old.  Please replace it with https://www.toda.is.i.nagoya-u.ac.jp/

**Comment by JeremyCCHsu** [comment]
Thanks for notification! 
However, I cannot access the [link](https://www.toda.is.i.nagoya-u.ac.jp/) somehow. 
Is there an alternative link to Toda lab's page?

![image](https://user-images.githubusercontent.com/16027371/63748617-48211a00-c8dc-11e9-9e96-97e2c09075fc.png)

**Comment by tats-u** [comment]
I CAN visit it without any problems.  I may have added the IP addresses of your ISP (e.g. HiNet) to the firewall.  Are you using HiNet?  It has many malicious crackers and disliked by quite a few server administrators in Japan.
However, I saw an article that it mostly monopolizes the FTTB(FTTH) market in Taiwan, but is it true?  If so, I may have to reset the access restriction.

**Comment by JeremyCCHsu** [comment]
I can access the web page now! Thanks!

**Comment by tats-u** [comment]
That's because I removed the FW rules related to HiNet.
